### ISSUE TITLE
yacman updates broke caravel

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#139]
I believe this error may be due to yacman updates:

```
[2019-12-10 12:35:18,369] INFO in caravel: Using token from the URL argument
[2019-12-10 12:35:18,373] INFO in helpers: Using environment variable -- /home/ns5bc/caravel.yaml
[2019-12-10 12:35:18,404] ERROR in caravel: Unhandled Exception: You can't call write on an object that was created in read-only mode.
Traceback (most recent call last):
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/caravel.py", line 87, in decorated
    return func(*args, **kwargs)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/caravel.py", line 222, in index
    globs.cc = globs.cc or parse_config_file()
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/helpers.py", line 211, in parse_config_file
    return CaravelConf(project_list_path)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/caravel_conf.py", line 71, in __init__
    self.populate_project_metadata({"name": lambda p: p.name}, missing_names, []).write()
  File "/home/ns5bc/.local/lib/python3.6/site-packages/yacman/yacman.py", line 158, in write
    raise OSError("You can't call write on an object that was created in read-only mode.")
OSError: You can't call write on an object that was created in read-only mode.
```

using caravel 0.13.2 (which is actually not released on github btw)

**Comment by michalstolarczyk** [comment]
yes, 0.13.2 is a development version: https://github.com/pepkit/caravel/pull/135

and it looks like `yacman` was not used in 0.13.1 at all so to fix this we'll probably just need to change one line here, e.g. use `CaravelConf` object in a context manager to write

**Comment by nsheff** [comment]
excellent.

**Comment by michalstolarczyk** [comment]
can you confirm if this works for you now? For example by running `caravel --demo`.  I'll make all the required releases if it does.

**Comment by nsheff** [comment]
Yes, this worked for me now.
