### ISSUE TITLE
Update to latest looper/peppy

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#140]
Lots of changes in looper/peppy. once we have those stably released again we should update caravel to be compatible.

```
caravel --version
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/caravel", line 6, in <module>
    from caravel.caravel import main
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/caravel.py", line 10, in <module>
    from .const import *
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/const.py", line 4, in <module>
    from looper import __version__ as LOOPER_VERSION, Sample as LooperSample
ImportError: cannot import name 'Sample'
```

**Comment by nsheff** [comment]
@stolarczyk took a look at this but it's a bit of work to revamp, so we decided to postpone this for a bit until we've made a bit of progress in perago and react, since caravel will inherit from these projects going forward. We should revist this toward the end of the year.
