### ISSUE TITLE
required looper version determination fails

### ISSUE THREAD

**Issue by michalstolarczyk** [pepkit/caravel#68]
Can we bound our `looper` req in the requirements file, then read this from there?

_Originally posted by @vreuter in https://github.com/pepkit/caravel/diffs_

**Comment by michalstolarczyk** [comment]
@vreuter, for some reason the `requirements` dir is not copied at `pip install` even though it's specified in the `MANIFEST` template. Do you know what might be the reasson?

This causes the `_get_looper_req` function to fail:


```
mstolarczyk@MichalsMBP:/Users/mstolarczyk/Uczelnia/UVA/code/caravel caravel -c example_caravel.yaml 
Traceback (most recent call last):
  File "/usr/local/bin/caravel", line 11, in <module>
    load_entry_point('caravel==0.2.dev0', 'console_scripts', 'caravel')()
  File "/Users/mstolarczyk/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/mstolarczyk/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/mstolarczyk/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/mstolarczyk/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/caravel/caravel.py", line 10, in <module>
    from const import *
  File "/Library/Python/2.7/site-packages/caravel/const.py", line 25, in <module>
    REQUIRED_LOOPER_VERSION = _get_looper_req()
  File "/Library/Python/2.7/site-packages/caravel/const.py", line 11, in _get_looper_req
    with open(reqs_file) as rf:
IOError: [Errno 2] No such file or directory: '/Library/Python/2.7/site-packages/requirements/requirements-all.txt'
```

Also, I have no clue why it worked for me before as I did not change the `MANIFEST` since then

**Comment by vreuter** [comment]
I'm not sure exactly what's going on yet, but it looks like it's checking a wrong path. There's no package name in that `IOError` message -- it's as if something like "caravel" or "looper" is missing, like there's an extra `os.path.dirname` call inserted. I might need to tweak that function -- I just wrote what first came to mind but it feels pretty hacky to implement as basically "go up two levels".

**Comment by michalstolarczyk** [comment]
I removed one `os.path.dirname` call, but then I guess we face the error I described above.

```
mstolarczyk@MichalsMBP:/Users/mstolarczyk/Uczelnia/UVA/code/looper caravel -c ../caravel/example_caravel.yaml 
Traceback (most recent call last):
  File "/Users/mstolarczyk/Library/Python/2.7/bin/caravel", line 11, in <module>
    load_entry_point('caravel==0.2.dev0', 'console_scripts', 'caravel')()
  File "/Users/mstolarczyk/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/mstolarczyk/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/mstolarczyk/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/mstolarczyk/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/mstolarczyk/Library/Python/2.7/lib/python/site-packages/caravel/caravel.py", line 10, in <module>
    from const import *
  File "/Users/mstolarczyk/Library/Python/2.7/lib/python/site-packages/caravel/const.py", line 25, in <module>
    REQUIRED_LOOPER_VERSION = _get_looper_req()
  File "/Users/mstolarczyk/Library/Python/2.7/lib/python/site-packages/caravel/const.py", line 11, in _get_looper_req
    with open(reqs_file) as rf:
IOError: [Errno 2] No such file or directory: '/Users/mstolarczyk/Library/Python/2.7/lib/python/site-packages/caravel/requirements/requirements-all.txt'
```

**Comment by michalstolarczyk** [comment]
Since the `requirements-all.txt` itself already assures the version of `looper` at `caravel` install I decided to allow for the missing `requirements/requirements-all.txt` file in case this happens. 
So, if the file is not found we skip the assurance.

**Comment by vreuter** [comment]
I can't reproduce this. For me `dev` branch of `caravel` installs fine.

**Comment by vreuter** [comment]
```
(py2) ~/code/caravel (dev) $ git log | head
commit 645edd848804b034598ebf2186305e71ed0cd8ee
Merge: 292f0ef 24a7f53
Author: Vince Reuter <vince.reuter@gmail.com>
Date:   Tue Mar 5 14:25:11 2019 -0500

    Merge branch 'dev' of github.com:pepkit/caravel into dev

commit 292f0ef9f2b7b919fc59935d856d6dc5cf94a14d
Author: Vince Reuter <vince.reuter@gmail.com>
Date:   Tue Mar 5 14:24:58 2019 -0500
(py2) ~/code/caravel (dev) $ pins
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Processing /home/vpr9v/code/caravel
Requirement already satisfied, skipping upgrade: flask in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from caravel==0.2.dev0) (1.0.2)
Requirement already satisfied, skipping upgrade: divvy in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from caravel==0.2.dev0) (0.1)
Requirement already satisfied, skipping upgrade: looper>0.10.0 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from caravel==0.2.dev0) (0.11.0.dev0)
Requirement already satisfied, skipping upgrade: peppy>=0.20 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from caravel==0.2.dev0) (0.20)
Requirement already satisfied, skipping upgrade: textile in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from caravel==0.2.dev0) (3.0.3)
Requirement already satisfied, skipping upgrade: Werkzeug>=0.14 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from flask->caravel==0.2.dev0) (0.14.1)
Requirement already satisfied, skipping upgrade: click>=5.1 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from flask->caravel==0.2.dev0) (7.0)
Requirement already satisfied, skipping upgrade: Jinja2>=2.10 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from flask->caravel==0.2.dev0) (2.10)
Requirement already satisfied, skipping upgrade: itsdangerous>=0.24 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from flask->caravel==0.2.dev0) (1.1.0)
Requirement already satisfied, skipping upgrade: nbsphinx in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from divvy->caravel==0.2.dev0) (0.4.2)
Requirement already satisfied, skipping upgrade: pandas>=0.20.2 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from divvy->caravel==0.2.dev0) (0.23.4)
Requirement already satisfied, skipping upgrade: pyyaml>=3.12 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from divvy->caravel==0.2.dev0) (3.13)
Requirement already satisfied, skipping upgrade: attmap>=0.2 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from divvy->caravel==0.2.dev0) (0.2)
Requirement already satisfied, skipping upgrade: colorama>=0.3.9 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from looper>0.10.0->caravel==0.2.dev0) (0.4.1)
Requirement already satisfied, skipping upgrade: six in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from textile->caravel==0.2.dev0) (1.12.0)
Requirement already satisfied, skipping upgrade: html5lib>=0.999999999 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from textile->caravel==0.2.dev0) (1.0.1)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from Jinja2>=2.10->flask->caravel==0.2.dev0) (1.1.0)
Requirement already satisfied, skipping upgrade: nbformat in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from nbsphinx->divvy->caravel==0.2.dev0) (4.4.0)
Requirement already satisfied, skipping upgrade: nbconvert!=5.4 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from nbsphinx->divvy->caravel==0.2.dev0) (5.3.1)
Requirement already satisfied, skipping upgrade: traitlets in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from nbsphinx->divvy->caravel==0.2.dev0) (4.3.2)
Requirement already satisfied, skipping upgrade: docutils in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from nbsphinx->divvy->caravel==0.2.dev0) (0.14)
Requirement already satisfied, skipping upgrade: sphinx>=1.6 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from nbsphinx->divvy->caravel==0.2.dev0) (1.8.3)
Requirement already satisfied, skipping upgrade: pytz>=2011k in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from pandas>=0.20.2->divvy->caravel==0.2.dev0) (2018.9)
Requirement already satisfied, skipping upgrade: numpy>=1.9.0 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from pandas>=0.20.2->divvy->caravel==0.2.dev0) (1.16.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.5.0 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from pandas>=0.20.2->divvy->caravel==0.2.dev0) (2.7.5)
Requirement already satisfied, skipping upgrade: webencodings in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from html5lib>=0.999999999->textile->caravel==0.2.dev0) (0.5.1)
Requirement already satisfied, skipping upgrade: jupyter-core in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from nbformat->nbsphinx->divvy->caravel==0.2.dev0) (4.4.0)
Requirement already satisfied, skipping upgrade: jsonschema!=2.5.0,>=2.4 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from nbformat->nbsphinx->divvy->caravel==0.2.dev0) (2.6.0)
Requirement already satisfied, skipping upgrade: ipython-genutils in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from nbformat->nbsphinx->divvy->caravel==0.2.dev0) (0.2.0)
Requirement already satisfied, skipping upgrade: entrypoints>=0.2.2 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from nbconvert!=5.4->nbsphinx->divvy->caravel==0.2.dev0) (0.3)
Requirement already satisfied, skipping upgrade: testpath in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from nbconvert!=5.4->nbsphinx->divvy->caravel==0.2.dev0) (0.4.2)
Requirement already satisfied, skipping upgrade: mistune>=0.7.4 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from nbconvert!=5.4->nbsphinx->divvy->caravel==0.2.dev0) (0.8.4)
Requirement already satisfied, skipping upgrade: bleach in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from nbconvert!=5.4->nbsphinx->divvy->caravel==0.2.dev0) (3.1.0)
Requirement already satisfied, skipping upgrade: pygments in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from nbconvert!=5.4->nbsphinx->divvy->caravel==0.2.dev0) (2.3.1)
Requirement already satisfied, skipping upgrade: pandocfilters>=1.4.1 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from nbconvert!=5.4->nbsphinx->divvy->caravel==0.2.dev0) (1.4.2)
Requirement already satisfied, skipping upgrade: enum34; python_version == "2.7" in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from traitlets->nbsphinx->divvy->caravel==0.2.dev0) (1.1.6)
Requirement already satisfied, skipping upgrade: decorator in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from traitlets->nbsphinx->divvy->caravel==0.2.dev0) (4.3.0)
Requirement already satisfied, skipping upgrade: sphinxcontrib-websupport in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from sphinx>=1.6->nbsphinx->divvy->caravel==0.2.dev0) (1.1.0)
Requirement already satisfied, skipping upgrade: babel!=2.0,>=1.3 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from sphinx>=1.6->nbsphinx->divvy->caravel==0.2.dev0) (2.6.0)
Requirement already satisfied, skipping upgrade: imagesize in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from sphinx>=1.6->nbsphinx->divvy->caravel==0.2.dev0) (1.1.0)
Requirement already satisfied, skipping upgrade: setuptools in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from sphinx>=1.6->nbsphinx->divvy->caravel==0.2.dev0) (40.6.3)
Requirement already satisfied, skipping upgrade: packaging in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from sphinx>=1.6->nbsphinx->divvy->caravel==0.2.dev0) (19.0)
Requirement already satisfied, skipping upgrade: requests>=2.0.0 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from sphinx>=1.6->nbsphinx->divvy->caravel==0.2.dev0) (2.21.0)
Requirement already satisfied, skipping upgrade: typing; python_version < "3.5" in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from sphinx>=1.6->nbsphinx->divvy->caravel==0.2.dev0) (3.6.6)
Requirement already satisfied, skipping upgrade: alabaster<0.8,>=0.7 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from sphinx>=1.6->nbsphinx->divvy->caravel==0.2.dev0) (0.7.12)
Requirement already satisfied, skipping upgrade: snowballstemmer>=1.1 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from sphinx>=1.6->nbsphinx->divvy->caravel==0.2.dev0) (1.2.1)
Requirement already satisfied, skipping upgrade: functools32; python_version == "2.7" in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->nbsphinx->divvy->caravel==0.2.dev0) (3.2.3.post2)
Requirement already satisfied, skipping upgrade: configparser>=3.5; python_version == "2.7" in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from entrypoints>=0.2.2->nbconvert!=5.4->nbsphinx->divvy->caravel==0.2.dev0) (3.5.0)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from packaging->sphinx>=1.6->nbsphinx->divvy->caravel==0.2.dev0) (2.3.1)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from requests>=2.0.0->sphinx>=1.6->nbsphinx->divvy->caravel==0.2.dev0) (1.24.1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from requests>=2.0.0->sphinx>=1.6->nbsphinx->divvy->caravel==0.2.dev0) (2018.11.29)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from requests>=2.0.0->sphinx>=1.6->nbsphinx->divvy->caravel==0.2.dev0) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /home/vpr9v/venvs/py2/lib/python2.7/site-packages (from requests>=2.0.0->sphinx>=1.6->nbsphinx->divvy->caravel==0.2.dev0) (2.8)
Building wheels for collected packages: caravel
  Building wheel for caravel (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-PQHa43/wheels/d2/b5/f1/e2f252b4c4bbc988e1c12d6aee8f39147ec4ef775a869007bd
Successfully built caravel
Installing collected packages: caravel
  Found existing installation: caravel 0.2.dev0
    Uninstalling caravel-0.2.dev0:
      Successfully uninstalled caravel-0.2.dev0
Successfully installed caravel-0.2.dev0
```

**Comment by michalstolarczyk** [comment]
Yeah, it installs just fine for me as well, but the `requirements` dir isn't copied. And therefore the `_get_looper_req` fucntion can determine the `REQUIRED_LOOPER_VERSION` constant.

is it copied in your case?

**Comment by vreuter** [comment]
Ah OK got it -- sorry, thought you were hitting the error on install attempt. No, it's not copied for me either. Hmm....I think it's atypical to include it with the distribution...we can leave the redeclaration, though it is frustrating that the reqs aren't included...I'm not sure why.

**Comment by vreuter** [comment]
Anyway, that's all to say that yes, it's also the case that it's _not_ copied for me, so I think our installations are behaving similarly if not identically.

**Comment by michalstolarczyk** [comment]
I think I found a solution. I moved the `requirements` dir down to the `caravel` and then adjusted the path for the dependencies reading included them with in the `setup` call in `setup.py`:

https://github.com/pepkit/caravel/blob/49dac014f7b04b05f9dd8405b3c6493eb1b52a42/setup.py#L60

Does absence of `requirements` in the place it was before affect anything?

**Comment by vreuter** [comment]
I don't think it should. It may've previously been the case that the Python package construction and deployment infrastructure with `setuptools` and such needed it in a particular place, but I think now it's the norm--or at least we are--explicitly parsing the dependencies and communicating them to `setup`. As long as the installation succeeds with the updated placement, I think we're good. Nice!

**Comment by nsheff** [comment]
I think readthedocs wanted them in a particular place, but you can also customize it away from default so it's no big deal. plus we're not using readthedocs anymore...
