### ISSUE TITLE
viewing summary in debug mode

### ISSUE THREAD

**Issue by michalstolarczyk** [pepkit/caravel#82]
When running the app in the debug mode, the the summary page can't be viewed. This is due to a problem with blueprint registering. It has already been reported elsewhere: https://github.com/alexmclarty/mirror/issues/6

**Comment by michalstolarczyk** [comment]
After commenting out of the `try ... except` block in the `_background_summary_notice` route I get this error:
```
[2019-03-11 19:23:59,960] ERROR in caravel: Unhandled Exception: A setup function was called after the first request was handled.  This usually indicates a bug in the application where a module was not imported and decorators or other functionality was called too late.
To fix this make sure to import all your view modules, database models and everything related at a central place before the application starts serving requests.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "../../caravel/caravel.py", line 344, in background_summary_notice
    app.register_blueprint(psummary)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 59, in wrapper_func
    raise AssertionError('A setup function was called after the '
AssertionError: A setup function was called after the first request was handled.  This usually indicates a bug in the application where a module was not imported and decorators or other functionality was called too late.
To fix this make sure to import all your view modules, database models and everything related at a central place before the application starts serving requests.

```
