### ISSUE TITLE
command not found in namespace

### ISSUE THREAD

**Issue by michalstolarczyk** [pepkit/caravel#85]
```
mstolarczyk@MichalsMBP:/Users/mstolarczyk/Uczelnia/UVA/code/caravel ssh -L 5001:localhost:5001 mjs5kd@interactive.hpc.virginia.edu "cd $REMOTE_CODEBASE; caravel -c caravel/dna_meth.yaml --port 5001"
Warning: the RSA host key for 'interactive.hpc.virginia.edu' differs from the key for the IP address '128.143.245.141'
Offending key for IP in /Users/mstolarczyk/.ssh/known_hosts:3
Matching host key in /Users/mstolarczyk/.ssh/known_hosts:4
Are you sure you want to continue connecting (yes/no)? yes
mjs5kd@interactive.hpc.virginia.edu's password: 
Profile activated
 * Serving Flask app "caravel.caravel" (lazy loading)
 * Environment: production

Caravel is protected with a token.
Copy this link to your browser to authenticate:

 http://localhost:5001/?token=U37TY5V4H43FH1Y

   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5001/ (Press CTRL+C to quit)
[2019-03-13 19:49:12,090] INFO in caravel: Using token from the URL argument
[2019-03-13 19:49:12,118] INFO in caravel: CSRF token retrieved from the session
127.0.0.1 - - [13/Mar/2019 19:49:12] "GET /?token=U37TY5V4H43FH1Y HTTP/1.1" 200 -
[2019-03-13 19:49:13,217] INFO in caravel: Using the token from the session
Using default config file, no global config file provided in environment variable(s): ['DIVCFG', 'PEPENV']
Loading divvy config file: /home/mjs5kd/.local/lib/python2.7/site-packages/divvy/submit_templates/default_compute_settings.yaml
Available packages: default, local, slurm
Activating compute package 'default'
Setting sample sheet from file '/home/mjs5kd/code/dnameth_pipelines/examples/microtest_annotation.csv'
[2019-03-13 19:49:13,955] INFO in caravel: CSRF token retrieved from the session
127.0.0.1 - - [13/Mar/2019 19:49:13] "POST /process HTTP/1.1" 200 -
127.0.0.1 - - [13/Mar/2019 19:49:14] "GET /_background_summary_notice HTTP/1.1" 200 -
[2019-03-13 19:49:14,194] INFO in caravel: CSRF token retrieved from the session
127.0.0.1 - - [13/Mar/2019 19:49:14] "GET /_background_options?act=run HTTP/1.1" 200 -
[2019-03-13 19:49:15,919] INFO in caravel: Using the token from the session
[2019-03-13 19:49:15,919] INFO in caravel: The compute package was not selected, using 'default'.
Activating compute package 'default'
-------------- looper log --------------
Finding pipelines for protocol(s): WGBS, RRBS

Action: run

## [1 of 4] RRBS_human (RRBS)
[2019-03-13 19:49:16,077] ERROR in caravel: Unhandled Exception: 'Namespace' object has no attribute 'command'
Unhandled Exception: 'Namespace' object has no attribute 'command'
Traceback (most recent call last):
  File "/home/mjs5kd/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mjs5kd/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mjs5kd/.local/lib/python2.7/site-packages/caravel/caravel.py", line 94, in decorated
    return func(*args, **kwargs)
  File "/home/mjs5kd/.local/lib/python2.7/site-packages/caravel/caravel.py", line 381, in action
    run_looper(prj=p, args=args, act=act, log_path=log_path, logging_lvl=logging_lvl)
  File "/home/mjs5kd/.local/lib/python2.7/site-packages/caravel/helpers.py", line 269, in decorated
    func(*args, **kwargs)
  File "/home/mjs5kd/.local/lib/python2.7/site-packages/caravel/helpers.py", line 296, in run_looper
    run(args, None)
  File "/home/mjs5kd/.local/lib/python2.7/site-packages/looper/looper.py", line 342, in __call__
    rerun = args.command == "rerun"
AttributeError: 'Namespace' object has no attribute 'command'
```

**Comment by vreuter** [comment]
sorry; changes went into `looper` on `dev` that look like they broke something here in `caravel`

**Comment by michalstolarczyk** [comment]
thanks @vreuter, resolved
