### ISSUE TITLE
template error

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#91]
can't run current dev version of caravel and jinja version of looper:

```
caravel

Caravel is protected with a token.
Copy this link to your browser to authenticate:

 http://localhost:5000/?token=I7DF9E9OQNO3UD3

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2019-03-28 08:01:26,256] ERROR in caravel: Unhandled Exception: index.html
Traceback (most recent call last):
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/caravel/caravel.py", line 100, in decorated
    return func(*args, **kwargs)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/caravel/caravel.py", line 237, in index
    return render_template('index.html', projects=projects, reset_btn=reset_btn)
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/ns5bc/.local/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/ns5bc/.local/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: index.html

[2019-03-28 08:01:26,260] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/app.py", line 1518, in handle_user_exception
    return handler(e)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/caravel/caravel.py", line 135, in unhandled_exception
    return render_template('error.html', e=[e], types=[e.__class__.__name__]), 500
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/ns5bc/.local/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/ns5bc/.local/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: error.html
```

**Comment by michalstolarczyk** [comment]
can't reproduce it

but it looks like my yesterday's change of template directory name caused your error since the templates could not be found in your case. The path was adjusted in the app, so it should work

**Comment by michalstolarczyk** [comment]
the name of the templates directory has changed but I did not include it in the `MANIFEST.in` template

**Comment by nsheff** [comment]
thanks.
