### ISSUE TITLE
caravel error

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#92]
```Caravel server encountered exception(s):

    Exception: Checked flag is only valid in caravel context

```

```
[2019-03-28 17:41:31,411] ERROR in caravel: Unhandled Exception: Checked flag is only valid in caravel context
Traceback (most recent call last):
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/caravel/caravel.py", line 100, in decorated
    return func(*args, **kwargs)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/caravel/caravel.py", line 284, in process
    actions = get_positional_args(blp(), sort=True)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/__init__.py", line 305, in build_parser
    action=_StoreBoolActionType, default=True, type=html_checkbox(checked=True),
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/parser_types.py", line 35, in html_checkbox
    raise Exception("Checked flag is only valid in caravel context")
Exception: Checked flag is only valid in caravel context
```

using latest dev caravel and jinja looper.

**Comment by nsheff** [comment]
actually looks like this is a looper error because looper is broken as well.
