### ISSUE TITLE
summarizer error in python 3

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#99]
I finally got a summary to complete (sort of) and it yielded this error:

```
## [9 of 9] b6_f9 (ATAC)
Using objects file: '/sfs/lustre/allocations/shefflab/processed//dura_macs/results_pipeline/b6_f9/objects.tsv'
using templates dir: /sfs/qumulo/qhome/ns5bc/.local/lib/python3.6/site-packages/looper/jinja_templates
create_object_html: cumulative_frip.html references nonexistent object files
create_object_html: fragment_distribution.html references nonexistent object files
[2019-04-09 09:44:26,129] ERROR in caravel: Unhandled Exception: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1134, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1240, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1256, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1494, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/caravel.py", line 100, in decorated
    return func(*args, **kwargs)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/caravel.py", line 443, in action
    run_looper(prj=p, args=args, act=act, log_path=log_path, logging_lvl=logging_lvl)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/helpers.py", line 283, in decorated
    func(*args, **kwargs)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/helpers.py", line 317, in run_looper
    _render_summary_pages(prj)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/helpers.py", line 351, in _render_summary_pages
    footer=footer)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/html_reports.py", line 640, in create_index_html
    self.create_status_html(objs, stats, self.reports_dir, navbar_reports, footer))
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/html_reports.py", line 464, in create_status_html
    t = _pd.read_table(log_file, header=None, names=['key', 'value'])
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/site-packages/pandas/io/parsers.py", line 446, in _read
    data = parser.read(nrows)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/site-packages/pandas/io/parsers.py", line 1036, in read
    ret = self._engine.read(nrows)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/site-packages/pandas/io/parsers.py", line 1848, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 876, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 891, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 968, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1094, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1141, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1240, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1256, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1494, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

127.0.0.1 - - [09/Apr/2019 09:44:26] "POST /action HTTP/1.1" 500 -

```

**Comment by michalstolarczyk** [comment]
this issue is project specific and I could not reproduce it, but maybe the latest commit resolves it

**Comment by nsheff** [comment]
this was a python3 error. did you try it in python 3?

**Comment by michalstolarczyk** [comment]
> even using python3.6. 

yes
